[package]
name = "orb"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "^1.0"
clap = { version = "4.1", features = ["derive"] }
zen-engine = "0.5.1"
zen-expression = "0.5.1"
csv = "1.1"
